### ISSUE TITLE
Import location from exif

### ISSUE THREAD

**Issue by samwilson** [samwilson/twyne#116]
Lat and long should be extracted from exif GPS attrs.

**Comment by revi** [comment]
Also an option to *not* infer location from EXIF would be desirable because I sometimes take photos from home and I do not want to reveal my home location.

**Comment by samwilson** [comment]
That's a good idea. That'd also mean that the original image at `/PxxF.jpg` shouldn't be served; I've created #126 for that.

One way to do it could be to look for a tag that's connected to [Q104027759 Location withheld](https://www.wikidata.org/wiki/Q104027759), and not reveal locations for any posts with that tag (other than to an admin). Then, when importing or uploading, it'd just be a matter of adding that tag.

**Comment by samwilson** [comment]
The first part of this (importing the location from Exif) is done, in #132.

**Comment by samwilson** [comment]
The hiding of location data will be done in #134.
