### ISSUE TITLE
AWS secret should be hidden from view

### ISSUE THREAD

**Issue by revi** [samwilson/twyne#122]
For now, AWS secret (which is equivalent for password) is visible. Should be treated as password (or become config file value).

<img width="314" alt="image" src="https://user-images.githubusercontent.com/7630875/132100269-a8bd782f-801c-407e-859a-51b48843ff4c.png">

**Comment by samwilson** [comment]
I'll move the filesystem config variables to the `.env.local` file; they're safer there, and there's no real need for them to be easily changeable via the UI.

**Comment by samwilson** [comment]
I've started this: #127

**Comment by samwilson** [comment]
Fixed. Sites will break now when upgraded, until the config is moved to `.env.local`, but I figure that's probably okay because Twyne is still not 1.0!
