### ISSUE TITLE
AWS Bucket is used as endpoint

### ISSUE THREAD

**Issue by revi** [samwilson/twyne#123]
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/7630875/132100486-d854be57-4cfd-4ddb-aa21-6606d8ce27f7.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/7630875/132100502-3ec8c275-382c-494e-af0c-8ec9654b5e0f.png">

`//revi-twyne/revi-twyne` is wrong. Should be `s3.us-east-1.amazonaws.com`.

**Comment by samwilson** [comment]
Could it be that it wants the `https://` in the endpoint URL? I'm mainly testing with Digital Ocean, so I guess there could be some differences, but I wouldn't have thought it'd be with something so fundamental.

**Comment by revi** [comment]
Had to move the host and I had no time to make it work on new host.

OK, adding https:// to the config worked ([P2](https://revi.blog/P2)) (but I needed to install `exiftool` and `imagemagick` which was not mentioned in requirements list in docs).
