### ISSUE TITLE
Lists (numbered and un-numebered) displaying incorrectly

### ISSUE THREAD

**Issue by revi** [samwilson/twyne#155]
Raw text:

```markdown
1. 의뢰 수주권은 매일 9시와 21시에 3개씩 충전됨 (하루 6개).
2. 의뢰 수주권은 100개 이상 차지 않음.
3. 따라서 6x14=84개를 납품하여 잔여 의뢰 수주권을 16개로 만들면 2주, 14일 주기로 의뢰 수주권이 정확히 100개가 된다.
```

What's displayed at [P103](https://revi.blog/P103):

![image](https://user-images.githubusercontent.com/7630875/152614916-89fbee95-efcf-4a70-8ac6-0c82ad5f798d.png)

Even without Korean knowledge you will notice the line 2 is nested, which is not the way it was written.

**Comment by revi** [comment]
Actually, for that matter, bullet point lists also displays weird:

```markdown
2021년 3월 기준임! 글 보시는 시점에는 내용이 다를 수 있음. 나 때는 이랬다는 정도의 이야기입니다.

* 검사를 한 보건소나 병원에서 전화가 옵니다. (음성이면 문자가 옴)
  * 가족이랑 같이 검사를 했는데 동거가족은 문자가 왔는데 시간이 지나도 난 안 온다? 이 시점부터 아 난 확진이구나 하고 마음의 준비를 시작하세요.
* 주소지 관할 보건소에서 연락이 옵니다. 역학조사를 위한 데이터를 요구합니다.
  * (검사한 날/증상 생긴 날부터 2일 전)~오늘까지의 카드 거래내역
  * 카드 실물 사진 (카드번호 보이게)
  * 본인 얼굴 사진을 달라고 합니다.
* 동선 조사를 한다고 하는데 나는 자가격리중에 증상발현이었어서 동선 조사할 것도 없이 집이었어서 모르겠네요.
* 생활치료센터나 병원이 배정됩니다. 격리통지서랑 같이 옵니다.
* 안내문자가 옵니다. 그거 읽어보면 됩니다. 대충 어디병원이나 어디 생활치료센터 갈 거라는 내용입니다. 갖고 들어가는 모든 물품은 휴대전화, 노트북, 충전기 빼고 아무것도 갖고 나올 수 없습니다. 다 나올 때 주는 봉투에 쑤셔넣고 나와야 합니다. 나올 때 같이 나올 수 있는 건 몸뚱아리, 핸드폰, 노트북, 충전기 밖에 없습니다. 옷도 (속옷 포함) 태웁니다. 먹던 약 있으면 약 2-3주치를 들고 가세요. 고혈압약은 성분명을 알아야 병원이나 센터에서 처방해 줄 수 있습니다.
* 이송을 위한 차가 오는데, 계단으로 걸어 내려가야 합니다. 그리고 이송 차가 언제올지 아무도 모르므로 미리미리 준비해두고 가지고 나갈 준비를 해 두세요. 까먹고 뭐 안들고가면 없는 대로 살아야 합니다. (특히 병원에서 이불 안 주는 경우 많음)

퇴소 기준은 병원/센터마다 다르지만 대개 병원은 의사 맘대로고 센터는 증상 없이 10일 넘어가면 내보내 줍니다.
```

[Displays as]:
(https://revi.blog/P35):
![image](https://user-images.githubusercontent.com/7630875/152615240-d5c4979d-e26a-49b5-a7bb-70c73be48bf5.png)

Multiple nested bullet lists are merged into one line, and nested bullet list is not recognized at all.

**Comment by samwilson** [comment]
You're right, this is no good! Sorry.

I have a plan afoot to completely overhaul the text parsing, and will try to get this fixed soon.

**Comment by samwilson** [comment]
The first part of this is fixed. The nested lists will take a bit longer...

**Comment by revi** [comment]
Looks like twyne 0.37.0 still disagrees.

```markdown
1. 친구 목록에서 "숨김 친구"로 등록
2. 카카오톡 설정
3. "친구"
4. "숨김친구 관리"
5. 삭제할 친구 선택
6. "관리 "
7. "삭제" 하면 "연락처에 등록되어 있어도 카카오톡 친구로 추가되지 않지만 메시지는 받을 수 있습니다" 경고문 후 삭제.
```

Screenshot (via phone):
![EF52EA9A-34CE-42F1-AC9C-30608349503B](https://user-images.githubusercontent.com/7630875/158280210-8b22d71e-353f-4654-9b28-f35af273b22b.png)

**Comment by samwilson** [comment]
I've switched to using the [League/CommonMark](https://commonmark.thephpleague.com) package to render Markdown, so it should all be much better now! Will make a new release shortly...
