### ISSUE TITLE
Contact page's Posts list displays the first 100 posts, not most recent 100 posts

### ISSUE THREAD

**Issue by revi** [samwilson/twyne#177]
As of the writing (w/ v.0.38.0), [contact: revi](https://revi.blog/C1) displays the P2 (the oldest possible pages in my archive) at the top, when P174 is currently the most recent articles.
![image](https://user-images.githubusercontent.com/7630875/176947869-d2ebcf00-d184-4e1f-8cb9-9e6938c91a36.png)

**Comment by samwilson** [comment]
This is fixed now, and will be in the next release.
