### ISSUE TITLE
New user (me) would like to be able to add a comment or three

### ISSUE THREAD

**Issue by foxandrewd** [samwilson/twyne#51]
Hi Sam,
My name's Andy, it's nice to meet you.
I just discovered your website (https://samwilson.id.au) and Twyne (Awesome work btw!!!)
I'd like to be able to add Comments to Posts. Is that something you're interested in much, or are open to exploring in the future? It may represent something akin to a MegaFeature though I'm assuming? And your time isn't limitless...

Also I found this dba.Stackexchange thread which may be relevant to your Question Post regarding how to add an index to a nullable POINT field in MySQL:

https://dba.stackexchange.com/questions/43062/how-to-design-indexes-for-columns-with-null-values-in-mysql

Are you currently utilising the InnoDB or the MyISAM database engine within MySQL? This point of differentiation certainly could have the potential to make a difference, I think.

Can I Zoom-Attend the Wikimedia Australia event: "(WA) 2020 December 3, Thursday — WikiClubWest at Riff (19) — Riff, 45 St Georges Terrace, Perth. 5.00 pm to 8.00 pm Perth WA Time."

If remote attendance weren't possible for some reason I'll need to arrange my flights MEL<=>PER within a very tight timeframe, so please get back to me quickly if at all possible.

Many Thanks for your Time.
All the best,
Andy
(fox.andrew.d@gmail.com)

**Comment by samwilson** [comment]
Hi Andy! Thanks for checking out Twyne. Have you been able to install it? Any suggestions for how to make that easier?

I do indeed have plans for adding commenting (#34). My idea is to make it a bit like Twitter, in that a comment is itself a post. I'm still figuring out the display, but I think it'll mostly work. One core part of the [indieweb](https://indieweb.org/) is that it should be possible to [POSSE](https://indieweb.org/POSSE), and so I think comments having the same features of posts would help with that (i.e. they could link to wherever they reside on other sites, or list their syndication places (#42)).

As for the WMAU meetup tonight, we can certainly enable remote attendance! I'd recommend not trying to fly from Melbourne! :-) I don't think it's going to be a big group tonight (it's a fortnightly thing, and sometimes not many people come, especially at this time of year). I'll send you an email.

Thanks for the info about databases, I'll look into it. I've got the CI tests running on multiple DBMSs, so should look at adding different engines too, just to keep everything as flexible as possible.

**Comment by samwilson** [comment]
I think the rest of the reply functionality will be done with Webmentions, in #56, and the database testing in #58.
